; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\ddu00001\AppData\Local\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
